### ISSUE TITLE
Restore fails on M1 Mac

### ISSUE THREAD

**Issue by ksilz** [sdeleuze/spring-boot-crac-demo#2]
I have a 2021 MacBook Pro with M1 Max. Running `checkpoint.sh` works, but `restore.sh` throws an error:
```
./restore.sh
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

Following the suggestion of this [SO question](https://stackoverflow.com/a/71611002/3574), I added ` --platform=linux/amd64` to the `FROM` of the `Dockerfile` and the two `docker run` commands in `checkpoint.sh` and `restore.sh`. As before, `checkpoint.sh` goes through just fine, but not `restore.sh`:
```
./restore.sh
Error (criu/kerndat.c:210): Can't stat self map_files 2: No such file or directory
Error (criu/kerndat.c:1522): kerndat_get_shmemdev failed when initializing kerndat.
Error (criu/crtools.c:260): Could not initialize kernel features detection.
```

How can I run `restore.sh` on my M1 Max?

**Comment by sdeleuze** [comment]
Hi, I am on Linux so I can't really try, but maybe you can try to use the ARM build of the CRaC-enabled JDK [here](https://github.com/sdeleuze/spring-boot-crac-demo/blob/main/Dockerfile#L6) and see how it goes. Feel free to provide a PR that support both using a paramterized Dockerfile.

**Comment by ksilz** [comment]
Does the CRaC integration with Spring Boot require the Azul CRaC-enabled JDK? Or could I use, say, Temurin?

**Comment by sdeleuze** [comment]
No specific dependency on Azul, but it requires a CRaC-enabled JDK. Has Temurin published such CRaC enabled build?

**Comment by ksilz** [comment]
I don't think Temurin has. I'll try the ARM build later this week (got music concerts today, tomorrow, and on Friday).

**Comment by sdeleuze** [comment]
Notice we observe segfaults on M1/M2, we have reported this issue to Azul.

**Comment by ksilz** [comment]
@sdeleuze Sorry for not getting back here earlier! While working on my [InfoQ news item about CRaC](https://www.infoq.com/news/2023/06/crac-cracks-mainstream-adoption), I confirmed with Simon Ritter that you **indeed** need a CRaC-enabled JRE to use CRaC.

**Comment by sdeleuze** [comment]
SegFault on Mac should be fixed shortly, so I reopen this issue and will close it once we have a version that fixes this issue available + a confirmation it works. Getting CRaC working on aarch64 is very important because it already has constraints related to mandatory Linux, if you add the "x86 only" one, it becomes very frustrating, so let's make sure this is fixed asap.

**Comment by sdeleuze** [comment]
I have been able to validate it now works with the latest AZUL CRaC JDK committed.
