### ISSUE TITLE
spring.main.cloud-platform effect

### ISSUE THREAD

**Issue by JulienHoullier** [sdeleuze/spring-boot-crac-demo#5]
Hello,

Sorry to bother with a question instead of an issue but i saw that the Spring boot parameter spring.main.cloud-platform is set to Kubernetes.

Is there a chance that the application after restore will be able to still have some dynamic configuration ?  
In a K8S classic PROD deployment, lots of configuration are passed through configMap as env to the POD to provide customization of the JAR. A simple example is the DB URI. I tested to set a SERVER_PORT=8081 and the Checkpoint image is not taking it into account.

In real life use case changing the SERVER_PORT is not important, but other configuration will be important. I remember to read about checkpoint created with SPring BOOt -Dspring.context.checkpoint=onRefresh will be able to load configuration but i cannot make it happens.

Thanks for your guidance

**Comment by sdeleuze** [comment]
Hi, sorry for the delay. This is sadly not possible out of the box but you can have such dynamic update of the configuration post-restoration thanks to Spring Cloud, see [this section](https://spring.io/blog/2023/10/16/runtime-efficiency-with-spring#jvm-checkpoint-restore-scale-to-zero-with-spring-and-project-crac) of my related blog post for more details. CDS provide more flexibility in term of configuration and may suit better to your needs.
